### ISSUE TITLE
decrypt() error in Tutorial Notebook "Paillier Encrypted Linear Classification Example"

### ISSUE THREAD

**Issue by borkjt9** [OpenMined/Capsule#24]
The line `model = model.decrypt()` returns the error "decrypt() missing 1 required positional argument: 'prikey'".

In the Syft library, decrypt requires the parameter 'private key'. Therefore I think this line should be changed to `model = model.decrypt(capsule)`.

I am happy to update if necessary.

**Comment by aradhyamathur** [comment]
is the error in the following tutorial https://github.com/OpenMined/PySyft/blob/master/notebooks/Syft%20-%20Paillier%20Encrypted%20Linear%20Classification.ipynb ?

**Comment by borkjt9** [comment]
Yes.

**Comment by aradhyamathur** [comment]
It would be better if u submit the issue in PySyft project itself and submit the PR for same :)
